name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write
      actions: write
      deployments: write

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'

      - name: Restore NuGet packages
        run: dotnet restore Additional.sln

      - name: Build C# Project
        run: dotnet build --configuration Release Additional.sln

      - name: Publish WPF Application with ClickOnce
        run: dotnet publish Additional/Additional.csproj --configuration Release /p:PublishUrl="publish\\" /p:InstallUrl="https://yourdomain.com/install/" /p:PublisherName="Ian Ross Williams" /p:ApplicationVersion="1.0.0.${{ github.run_number }}" /p:PublishSingleFile=true
        shell: pwsh

      - name: Zip the ClickOnce publish output
        run: Compress-Archive -Path publish/* -DestinationPath ClickOnce.zip
        shell: pwsh

      - name: Upload ClickOnce.zip as artifact
        uses: actions/upload-artifact@v2
        with:
          name: clickonce-artifact
          path: ClickOnce.zip

  release:
    needs: build
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Download ClickOnce artifact
        uses: actions/download-artifact@v2
        with:
          name: clickonce-artifact
          path: .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload ClickOnce Installer to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ClickOnce.zip
          asset_name: ClickOnce.zip
          asset_content_type: application/zip
