name: Build Installer with Inno Setup

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Inno Setup
      run: choco install innosetup

    - name: Compile Inno Setup Script
      run: ISCC.exe ./AdditionalPackaging.iss